# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from distutils.core import setup


NAME = "mindbody_api",
VERSION = "1.0.0"
REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]


setup(
    name=NAME,
    packages=[NAME],
    version=VERSION,
    description="MINDBODY Public API",
    author_email="mmgladki@gmail.com",
    url="https://github.com/mgladki/API-Examples",
    keywords=["Swagger", "MINDBODY Public API"],
    install_requires=REQUIRES,
    include_package_data=True,
    long_description="""\
    Mindbody Public API v6 (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501
    """,
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: BSD 2-Clause "Simplified" License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        ],
)
